[package]
name = "squirrels"
version = "0.0.1"
edition = "2021"


[lib]
name = "squirrels"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
panic = 'abort'

[dependencies.pyo3]
version = "0.23.3"
